import type { Metadata } from 'next'
import { ReactNode } from 'react'
import './globals.css'
import NavBar from '@/app/NavBar'

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body>
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  )
}
